# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('tarefa_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa_nome', models.CharField(max_length=120)),
                ('tarefa_descricao_inicio', models.DateField()),
                ('concluido', models.BooleanField(verbose_name='Concluido')),
            ],
        ),
    ]
