# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_auto_20180302_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('conta_id', models.AutoField(primary_key=True, serialize=False)),
                ('conta_nome', models.CharField(max_length=200)),
                ('conta_data_vencimento', models.DateField()),
                ('pago', models.BooleanField(verbose_name='Pago')),
            ],
        ),
    ]
