# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_contas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contas',
            new_name='Conta',
        ),
    ]
